amazon:
  partnerTag: "AMAZON_PARTNER_TAG"
  accessKey: "AMAZON_ACCESS_KEY"
  secretKey: "AMAZON_SECRET_KEY"

database:
  connectionUrl: "DB_CONNECTION_URL"

redis:
  connectionUrl: "REDIS_CONNECTION_URL"
