amazon:
  partnerTag: "AMAZON_PARTNER_TAG"
  accessKey: "AMAZON_ACCESS_KEY"
  secretKey: "AMAZON_SECRET_KEY"

database:
  host: "DB_HOST"
  port: "DB_PORT"
  user: "DB_USER"
  password: "DB_PASSWORD"
  name: "DB_NAME"

redis:
  connectionUrl: "REDIS_CONNECTION_URL"

socksProxyManager:
  ssh:
    default:
      agent: "SSH_AUTH_SOCK"
