amazon:
  partnerTag: undefined
  partnerType: Associates
  accessKey: undefined
  secretKey: undefined
  host: webservices.amazon.de
  region: eu-west-1
  rateLimiter:
    minTime: 1500
    datastore: ioredis
    id: paapi
    dailyRequests: 8640

database:
  host: undefined
  port: undefined
  user: undefined
  password: undefined
  name: undefined

redis:
  connectionUrl: undefined
