amazon:
  partnerTag: undefined
  partnerType: Associates
  accessKey: undefined
  secretKey: undefined
  host: webservices.amazon.de
  region: eu-west-1
  rateLimiter:
    minTime: 1500
    datastore: ioredis
    id: paapi
    dailyRequests: 8640

database:
  host: undefined
  port: undefined
  user: undefined
  password: undefined
  name: undefined

redis:
  connectionUrl: undefined

socksProxyManager:
  socks:
    listen:
      host: 127.0.0.1
    auth: {}
      # username: socks-user
      # password: foobar

  ssh:
    default:
      username: root
    connections: []

queueing:
  importCategoryProducts:
    repeat:
      every: 120000
  importProductReviews:
    repeat:
      every: 30000

productReviewFetcher:
  socksGatewayProxy: "http://localhost:8080"
  rateLimiter:
    minTime: 2135
    maxConcurrent: 1
